### ISSUE TITLE
Links for Homepage and Docs

### ISSUE THREAD

**Issue by delsonting** [trivago/trivago-gtm-template#2]
The template has been approved and will appear in the Gallery in the next day. Recommendation to update your links in metadata.yaml:
Homepage: suggest using a link that describes what the tag does (generally company homepage or tag description)
Documentation: should be how to deploy the template and tag, suggestion to link to your github repo which appears to have good docs or your website if you have similar content there.

**Comment by Gaikanomer9** [comment]
Hello @delsonting! Thank you for the recommendation, updated the link to the documentation.
